name: build

run-name: ${{ github.actor }} is building

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v3
      - name: install dependencies
        run: 
          npm install
          npm run build
      - run: npm run e2e:headless
      - uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: e2e-tests
          path: cypress/videos