name: build

run-name: ${{ github.actor }} is building

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #cache clean
      - name: Cache clean
        run: npm cache clean --force
      - run: npm install
      #build
      - name: Build
        run: npm run build --if-present
      #start
      - name: Start
        run: npm start --if-present
