name: build

run-name: ${{ github.actor }} is building

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #cache clean and install dependencies
      - name: Cache clean
        run: npm cache clean --force
      - run: npm install
      #install wait-on
      - run: npm install wait-on
      #tests cypress
      - uses: actions/checkout@v3
      # run server
      - name: Serve
        run: npm run serve --if-present
      # wait for server to start
      - name: Wait for server
        run: npx wait-on http://localhost:3000
      - uses: cypress-io/github-action@v5
      # after the test run completes store videos and any screenshots
      - uses: actions/upload-artifact@v3
        # add the line below to store screenshots only on failures
        # if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      # stop serve
      - name: Stop serve
        run: npm run stop --if-present
      #build
      - name: Build
        run: npm run build --if-present
