name: build

run-name: ${{ github.actor }} is building

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #cache clean and install dependencies
      - name: Cache clean
        run: npm cache clean --force
      - run: npm install
      #start server
      - name: Start server
        run: npm start
      #tests cypress
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: true
      #stop server
      - name: Stop server
        run: npm stop
      #build
      - name: Build
        run: npm run build --if-present
